-- SHOW TABELS
-- 	Tables_in_ida4health
-- 	ageGroup  			x
-- 	cause				x
-- 	dataPoint
-- 	healthDataPoint
-- 	location            x
-- 	measurement
-- 	sex				    x
-- 	unit                x
-- 	unitGroup


INSERT INTO cause (name)
VALUES
    ('All causes of death (A00-Y89) excluding S00-T98'),
    ('Malignant neoplasm of colon, rectosigmoid junction, rectum, anus and anal canal'),
    ('Malignant neoplasm of trachea, bronchus and lung'),
    ('Malignant melanoma of skin'),
    ('Malignant neoplasm of breast'),
    ('Diabetes mellitus'),
    ('Mental and behavioral disorders (F00-F99)'),
    ('Other mental and behavioural disorders (remainder of F00-F99)'),
    ('Other ischaemic heart diseases'),
    ('Acute myocardial infarction including subsequent myocardial infarction'),
    ('Cerebrovascular diseases'),
    ('Chronic lower respiratory diseases'),
    ('Asthma and status asthmaticus');


INSERT INTO sex (name) 
VALUES     
    ('total'),     
    ('female'),     
    ('male'),     
    ('other');

INSERT INTO ageGroup (name, lower, uper) 
VALUES     
    ('up to 65', NULL, 64),     
    ('65 and up', 65, NULL),     
    ('0-4', 0, 4),     
    ('5-9', 5, 9),     
    ('10-14', 10, 14),     
    ('15-19', 15, 19),     
    ('20-24', 20, 24),     
    ('25-29', 25, 29),     
    ('30-34', 30, 34),     
    ('35-39', 35, 39),     
    ('40-44', 40, 44),     
    ('45-49', 45, 49),     
    ('50-54', 50, 54),     
    ('55-59', 55, 59),     
    ('60-64', 60, 64),     
    ('65-69', 65, 69),     
    ('70-74', 70, 74),     
    ('75-79', 75, 79),     
    ('80-84', 80, 84),     
    ('85-89', 85, 89),     
    ('90-94', 90, 94),     
    ('95-99', 95, 99),     
    ('100-104', 100, 104),     
    ('105-109', 105, 109),     
    ('110 and above', 110, NULL),     
    ('Total', NULL, NULL);

INSERT INTO location (name, description)
VALUES
    ("Åland", "By NUTS 2 classification"),
    ("Liechtenstein", "By NUTS 2 classification"),
    ("Ciudad de Ceuta", "By NUTS 2 classification"),
    ("Ciudad de Melilla", "By NUTS 2 classification"),
    ("Valle d'Aosta/Vallée d'Aoste", "By NUTS 2 classification"),
    ("Voreio Aigaio", "By NUTS 2 classification"),
    ("Ionia Nisia", "By NUTS 2 classification"),
    ("Região Autónoma dos Açores (PT)", "By NUTS 2 classification"),
    ("Região Autónoma da Madeira (PT)", "By NUTS 2 classification"),
    ("Dytiki Makedonia", "By NUTS 2 classification"),
    ("Molise", "By NUTS 2 classification"),
    ("Prov. Luxembourg (BE)", "By NUTS 2 classification"),
    ("Burgenland (AT)", "By NUTS 2 classification"),
    ("Mayotte", "By NUTS 2 classification"),
    ("La Rioja", "By NUTS 2 classification"),
    ("Ipeiros", "By NUTS 2 classification"),
    ("Notio Aigaio", "By NUTS 2 classification"),
    ("Corse", "By NUTS 2 classification"),
    ("Ticino", "By NUTS 2 classification"),
    ("Martinique", "By NUTS 2 classification"),
    ("Zeeland", "By NUTS 2 classification"),
    ("Vorarlberg", "By NUTS 2 classification"),
    ("Guadeloupe", "By NUTS 2 classification"),
    ("Prov. Brabant wallon", "By NUTS 2 classification"),
    ("Flevoland", "By NUTS 2 classification"),
    ("Algarve", "By NUTS 2 classification"),
    ("Drenthe", "By NUTS 2 classification"),
    ("Prov. Namur", "By NUTS 2 classification"),
    ("Malta", "By NUTS 2 classification"),
    ("Provincia Autonoma di Bolzano/Bozen", "By NUTS 2 classification"),
    ("Trier", "By NUTS 2 classification"),
    ("Provincia Autonoma di Trento", "By NUTS 2 classification"),
    ("Salzburg", "By NUTS 2 classification"),
    ("Kärnten", "By NUTS 2 classification"),
    ("Cantabria", "By NUTS 2 classification"),
    ("Groningen", "By NUTS 2 classification"),
    ("Nordjylland", "By NUTS 2 classification"),
    ("Kriti", "By NUTS 2 classification"),
    ("Luxembourg", "By NUTS 2 classification"),
    ("Friesland (NL)", "By NUTS 2 classification"),
    ("Bremen", "By NUTS 2 classification"),
    ("Bratislavský kraj", "By NUTS 2 classification"),
    ("Grad Zagreb", "By NUTS 2 classification"),
    ("Sjeverna Hrvatska", "By NUTS 2 classification"),
    ("Sostines regionas", "By NUTS 2 classification"),
    ("Zentralschweiz", "By NUTS 2 classification"),
    ("Sjælland", "By NUTS 2 classification"),
    ("Umbria", "By NUTS 2 classification"),
    ("La Réunion", "By NUTS 2 classification"),
    ("Prov. Limburg (BE)", "By NUTS 2 classification"),
    ("Cyprus", "By NUTS 2 classification"),
    ("Kypros", "By NUTS 2 classification"),
    ("Opolskie", "By NUTS 2 classification"),
    ("Saarland", "By NUTS 2 classification"),
    ("Zahodna Slovenija", "By NUTS 2 classification"),
    ("Gießen", "By NUTS 2 classification"),
    ("Leipzig", "By NUTS 2 classification"),
    ("Oberfranken", "By NUTS 2 classification"),
    ("Severozápad", "By NUTS 2 classification"),
    ("Prov. Liège", "By NUTS 2 classification"),
    ("Oberpfalz", "By NUTS 2 classification"),
    ("Limburg (NL)", "By NUTS 2 classification"),
    ("Overijssel", "By NUTS 2 classification"),
    ("Prov. Vlaams-Brabant", "By NUTS 2 classification"),
    ("Moravskoslezsko", "By NUTS 2 classification"),
    ("Nordwestschweiz", "By NUTS 2 classification"),
    ("Friuli-Venezia Giulia", "By NUTS 2 classification"),
    ("Strední Morava", "By NUTS 2 classification"),
    ("Prov. West-Vlaanderen", "By NUTS 2 classification"),
    ("Kassel", "By NUTS 2 classification"),
    ("Illes Balears", "By NUTS 2 classification"),
    ("Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest", "By NUTS 2 classification"),
    ("Praha", "By NUTS 2 classification"),
    ("Unterfranken", "By NUTS 2 classification"),
    ("Pest", "By NUTS 2 classification"),
    ("Prov. Hainaut", "By NUTS 2 classification"),
    ("Utrecht", "By NUTS 2 classification"),
    ("Chemnitz", "By NUTS 2 classification"),
    ("Marche", "By NUTS 2 classification"),
    ("Koblenz", "By NUTS 2 classification"),
    ("Liguria", "By NUTS 2 classification"),
    ("Prov. Oost-Vlaanderen", "By NUTS 2 classification"),
    ("Zürich", "By NUTS 2 classification"),
    ("Dresden", "By NUTS 2 classification"),
    ("Braunschweig", "By NUTS 2 classification"),
    ("Région lémanique", "By NUTS 2 classification"),
    ("Budapest", "By NUTS 2 classification"),
    ("Helsinki-Uusimaa", "By NUTS 2 classification"),
    ("Noord-Nederland", "By NUTS 2 classification"),
    ("Mittelfranken", "By NUTS 2 classification"),
    ("Hamburg", "By NUTS 2 classification"),
    ("Hovedstaden", "By NUTS 2 classification"),
    ("Tübingen", "By NUTS 2 classification"),
    ("Prov. Antwerpen", "By NUTS 2 classification"),
    ("Schwaben", "By NUTS 2 classification"),
    ("Alsace", "By NUTS 2 classification"),
    ("Wien", "By NUTS 2 classification"),
    ("Detmold", "By NUTS 2 classification"),
    ("Rheinhessen-Pfalz", "By NUTS 2 classification"),
    ("Gelderland", "By NUTS 2 classification"),
    ("Hannover", "By NUTS 2 classification"),
    ("País Vasco", "By NUTS 2 classification"),
    ("Canarias", "By NUTS 2 classification"),
    ("Bucuresti - Ilfov", "By NUTS 2 classification"),
    ("Freiburg", "By NUTS 2 classification"),
    ("Stockholm", "By NUTS 2 classification"),
    ("Noord-Brabant", "By NUTS 2 classification"),
    ("Münster", "By NUTS 2 classification"),
    ("Karlsruhe", "By NUTS 2 classification"),
    ("Área Metropolitana de Lisboa", "By NUTS 2 classification"),
    ("Noord-Holland", "By NUTS 2 classification"),
    ("Közép-Magyarország", "By NUTS 2 classification"),
    ("Warszawski stoleczny", "By NUTS 2 classification"),
    ("Arnsberg", "By NUTS 2 classification"),
    ("Berlin", "By NUTS 2 classification"),
    ("Zuid-Nederland", "By NUTS 2 classification"),
    ("Zuid-Holland", "By NUTS 2 classification"),
    ("Attiki", "By NUTS 2 classification"),
    ("Darmstadt", "By NUTS 2 classification"),
    ("Köln", "By NUTS 2 classification");


INSERT INTO unit (abbreviation, description)
VALUES
    ('km2', 'Square kilometers'),
    ('1', 'Count or Unit'),
    ('Euro/Person', 'Euro per Person'),
    ('Standardized rate', 'Standardized Rate'),
    ('ug/m3', 'Micrograms per Cubic Meter'),
    ('%', 'Percentage');
